apiVersion: apps/v1
kind: Deployment
metadata:
  name: voba
  labels:
    app: voba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voba
  template:
    metadata:
      labels:
        app: voba
    spec:
      containers:
      - name: voba
        image: docker.io/library/vb:1.0.2
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: http-voba
        env:
           - name: HostingBasePath
             valueFrom: 
               configMapKeyRef:
                 name: voba-config
                 key: UI.BasePath
